server:
  port: 8010

spring:
  application:
    #指定注册到eureka server上的服务名
    name: microservice-comsumer-movie
eureka:
  client:
    service-url:
      #指定eureka server通信地址，后缀eureka不能少
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
  instance:
    #是否注册ip到eureka server ，若不指定或设为false,则将主机名注册到eureka server
    prefer-ip-address: true