server:
  port: 8761
spring:
  application:
    name: microservice-discovery-eureka-ha
  security:
    user:
      name: user
      password: password123
eureka:
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/

---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8762/eureka/

---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/



